// <auto-generated />
namespace OpenQbit.Accounts.DAL.DataAccess.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class DbInit1 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(DbInit1));
        
        string IMigrationMetadata.Id
        {
            get { return "201706290931540_DbInit1"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
